import "package:flutter_dotenv/flutter_dotenv.dart";

/// Typed accessors for the runtime configuration loaded from `.env`.
///
/// The `.env` file is generated by `environment_config` from
/// [environment_config.yaml]. See the project README for details.
mixin EnvironmentConfig {
  /// Whether to use the in-memory mock notification service.
  ///
  /// When `false`, the app uses [ApiNotificationService]
  /// Defaults to `true`
  static bool get useMockNotifications {
    final raw = dotenv.env["USE_MOCK_NOTIFICATIONS"]?.toLowerCase();
    if (raw == null) return true;
    return raw != "false";
  }
}
